### ISSUE TITLE
Detection Line cannot be shown in the video 

### ISSUE THREAD

**Issue by editplus2020** [monemati/YOLOv8-DeepSORT-Streamlit#1]
Even if there are codes to show the detection line that objects pass through, it's still invisible.
Could you please advise how to make it happen?

**Comment by monemati** [comment]
> 

Hi, You can simply add below codes to "utils.py" in main repo at line 45 right after res_plotted = res[0].plot()

```
line = [(100, 500), (1050, 500)]
cv2.line(res_plotted, line[0], line[1], (46,162,112), 3)
```

For your own videos don't forget to change the "line" variable here in "utils.py" and in the /ultralytics/yolo/v8/detect/predict.py

**Comment by editplus2020** [comment]
@monemati, thanks. It solves the problem.
Btw, there are some defects of it, the programme will not stop automatically after running detection operation and results are not saved in a file.

**Comment by editplus2020** [comment]
@monemati, thanks. It solves the problem.
Btw, there are some defects of it, the programme will not stop automatically after running detection operation and results are not saved in a file.

**Comment by monemati** [comment]
> @monemati, thanks. It solves the problem. Btw, there are some defects of it, the programme will not stop automatically after running detection operation and results are not saved in a file.

Hi, You can use the "save_vid" branch. I changed "utils.py" a bit so it can save the output video. The program already stoping automatically after detection, I added a print to be more convenient.

**Comment by monemati** [comment]
> @monemati, thanks. It solves the problem. Btw, there are some defects of it, the programme will not stop automatically after running detection operation and results are not saved in a file.

Hi, You can use the "save_vid" branch. I changed "utils.py" a bit so it can save the output video. The program already stopping automatically after detection, I added a print to be more convenient.

**Comment by editplus2020** [comment]
Hello @monemati, I am new to yolo programming, and cannot find save_vid in the codes. Checked streamlit and there is no option of --save_vid.

**Comment by monemati** [comment]
> Hello @monemati, I am new to yolo programming, and cannot find save_vid in the codes. Checked streamlit and there is no option of --save_vid.

Hi, What I meant was new "save_vid" branch in my github repo. You can either use "git checkout save_vid" command or use this "utils.py" and replace it with your file:
https://github.com/monemati/YOLOv8-DeepSORT-Streamlit/blob/save_vid/utils.py

**Comment by editplus2020** [comment]
Hello @monemati, the saved file is not correct with very small size but I cannot find anything wrong with your codes. Maybe it's due to streamlit framework?

**Comment by monemati** [comment]
> Hello @monemati, the saved file is not correct with very small size but I cannot find anything wrong with your codes. Maybe it's due to streamlit framework?

Hi @editplus2020 I ran my code again and it is saving video properly. Are you getting any errors.
My Streamlit version is 1.22.0

**Comment by ovitorlima1** [comment]
Hi @monemati, how do i enable my gpu

**Comment by monemati** [comment]
> Hi @monemati, how do i enable my gpu

Hi @ovitorlima1, if you have cuda available on your device, the gpu will be used automatically.

**Comment by ovitorlima1** [comment]
A doubt @monemati, can I use this detection code for a custom model?

**Comment by monemati** [comment]
> A doubt @monemati, can I use this detection code for a custom model?

Hi @ovitorlima1, Yes you can use it on a custom model if it's based on YOLOv8.

**Comment by Leanse1** [comment]
Can you explain how to do on custom dataset because my best.pt is not getting loaded into streamlit

**Comment by monemati** [comment]
> Can you explain how to do on custom dataset because my best.pt is not getting loaded into streamlit

@Leanse1 Hi, you should add the model to config.py (# DL model config)
